# Best job.

- type: job
  id: ChiefMedicalOfficer
  name: job-name-cmo
  description: job-description-cmo
  playTimeTracker: JobChiefMedicalOfficer
  antagAdvantage: 6 # DeltaV - Reduced TC: Head of Staff
  requirements:
<<<<<<< HEAD
    - !type:RoleTimeRequirement
      role: JobChemist
      time: 18000 # Corvax-RoleTime
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 54000 # Corvax-RoleTime
=======
    - !type:CharacterPlaytimeRequirement
      tracker: JobChemist
      min: 14400 #DeltaV 4 hrs
#    - !type:RoleTimeRequirement # DeltaV - No Medical Doctor time requirement
#      role: JobMedicalDoctor
#      time: 21600 #6 hrs
    - !type:CharacterDepartmentTimeRequirement
      department: Medical
      min: 43200 # DeltaV - 12 hours
    - !type:CharacterOverallTimeRequirement
      min: 72000 # DeltaV - 20 hours
>>>>>>> a2133335fb6e574d2811a08800da08f11adab31f
  weight: 10
  startingGear: CMOGear
  icon: "JobIconChiefMedicalOfficer"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Medical
  - Command
  - Maintenance
  - Chemistry
  - ChiefMedicalOfficer
<<<<<<< HEAD
  - Brig
=======
  - Paramedic # DeltaV - Add Paramedic access
  - External # DeltaV - Paramedics need this access
  - Psychologist # DeltaV - Add Psychologist access
>>>>>>> a2133335fb6e574d2811a08800da08f11adab31f
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
<<<<<<< HEAD
=======
  - !type:AddComponentSpecial
    components:
    - type: CPRTraining
>>>>>>> a2133335fb6e574d2811a08800da08f11adab31f

- type: startingGear
  id: CMOGear
  equipment:
<<<<<<< HEAD
    id: CMOPDA
    ears: ClothingHeadsetCMO
    belt: ClothingBeltMedicalFilled
=======
    jumpsuit: ClothingUniformJumpsuitCMO
    back: ClothingBackpackCMOFilled
    shoes: ClothingShoesColorBrown
    id: CMOPDA
    ears: ClothingHeadsetCMO
    belt: ClothingBeltMedicalFilled
  innerClothingSkirt: ClothingUniformJumpskirtCMO
  satchel: ClothingBackpackSatchelCMOFilled
  duffelbag: ClothingBackpackDuffelCMOFilled
>>>>>>> a2133335fb6e574d2811a08800da08f11adab31f
