using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._EstacaoPirata.Xenobiology.UI;

[GenerateTypedNameReferences]
public sealed partial class SlimeGrinderMenu : FancyWindow
{
    private readonly SlimeGrinderBoundUserInterface _owner;

    public SlimeGrinderMenu(SlimeGrinderBoundUserInterface owner)
    {
        RobustXamlLoader.Load(this);

        _owner = owner;
    }
}

