<<<<<<< HEAD
﻿"Changes: Sprites":
- changed-files:
  - any-glob-to-any-file: '**/*.rsi/*.png'

"Changes: Map":
- changed-files:
  - any-glob-to-any-file:
    - 'Resources/Maps/*.yml'
    - 'Resources/Prototypes/Maps/*.yml'

"Changes: UI":
- changed-files:
  - any-glob-to-any-file: '**/*.xaml*'

"No C#":
- changed-files:
  # Equiv to any-glob-to-all as long as this has one matcher. If ALL changed files are not C# files, then apply label.
  - all-globs-to-all-files: "!**/*.cs"
=======
"Changes: Audio":
  - "**/*.ogg"
 
"Changes: C#":
  - "**/*.cs"

"Changes: Config":
  - "**/*.toml"
  - "**/*.config"
  - "*.json"
  - ".github/*.yml"
  - ".github/*.json"
  - ".vscode/*.json"
  - ".editorconfig"

"Changes: Documentation":
  - "**/*.xml"
  - "**/*.md"

"Changes: Localization":
- 'Resources/Locale/**/*.ftl'

"Changes: Map":
  - "Resources/Maps/**/*.yml"
  - "Resources/Prototypes/Maps/**/*.yml"

"Changes: Sprite":
  - "**/*.rsi/*.png"
  - "**/*.rsi/*.json"

"Changes: UI":
  - "**/*.xaml*"

"Changes: YML":
  - any: ["**/*.yml"]
    all: ["!Resources/Maps/**/*.yml", "!Resources/Prototypes/Maps/**/*.yml"]

"Changes: Workflow":
  - ".github/workflows/*.yml"
>>>>>>> a2133335fb6e574d2811a08800da08f11adab31f
