- type: accessLevel
  id: HeadOfSecurity
  name: id-card-access-level-head-of-security

- type: accessLevel
  id: Security
  name: id-card-access-level-security

- type: accessLevel
  id: Armory
  name: id-card-access-level-armory

# Delta V: Removes Brig access because redundant
#- type: accessLevel
#  id: Brig
#  name: id-card-access-level-brig

- type: accessLevel
  id: Detective
  name: id-card-access-level-detective

- type: accessGroup
  id: Security
  tags:
  - HeadOfSecurity
  - Security
  - Armory
  #- Brig #Delta V removed
  - Detective
  - Cryogenics
<<<<<<< HEAD
=======
  - Corpsman # DeltaV - add Corpsman access
>>>>>>> a2133335fb6e574d2811a08800da08f11adab31f

- type: accessGroup
  id: Armory
  tags:
  - Security
  - Armory
  # Brig #Delta V removed
