- type: job
  id: HeadOfPersonnel
  name: job-name-hop
  description: job-description-hop
  playTimeTracker: JobHeadOfPersonnel
  antagAdvantage: 6 # DeltaV - Reduced TC: Head of Staff
  requirements:
<<<<<<< HEAD
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 18000 # Corvax-RoleTime
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 18000 # Corvax-RoleTime
    - !type:DepartmentTimeRequirement
      department: Security
      time: 18000 # 5 hrs
    - !type:OverallPlaytimeRequirement
      time: 180000 # Corvax-RoleTime
  weight: 20
=======
    - !type:CharacterPlaytimeRequirement
      tracker: JobChef
      min: 14400 # DeltaV - 4 hours
    - !type:CharacterPlaytimeRequirement
      tracker: JobBartender
      min: 14400 # DeltaV - 4 hours
    - !type:CharacterPlaytimeRequirement
      tracker: JobJanitor
      min: 14400 # DeltaV - 4 hours
    - !type:CharacterDepartmentTimeRequirement # DeltaV - Civilian dept time requirement
      department: Civilian
      min: 72000 # 20 hours
    - !type:CharacterOverallTimeRequirement # DeltaV - Playtime requirement
      min: 90000 # 25 hours
  weight: 10 # DeltaV - Changed HoP weight from 20 to 10 due to them not being more important than other Heads
>>>>>>> a2133335fb6e574d2811a08800da08f11adab31f
  startingGear: HoPGear
  icon: "JobIconHeadOfPersonnel"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Command
  - HeadOfPersonnel
  - Bar
  - Service
  - Maintenance
  - Janitor
  - Theatre
  - Kitchen
#  - Chapel
  - Hydroponics
  - External
  - Cryogenics
  # I mean they'll give themselves the rest of the access levels *anyways*.
  # As of 15/03/23 they can't do that so here's MOST of the rest of the access levels.
  # Head level access that isn't their own was deliberately left out, get AA from the captain instead.
<<<<<<< HEAD
  - Chemistry
  - Engineering
  - Research
  - Detective
  - Armory
  - Salvage
  - Security
  - Brig
  - Lawyer
  - Cargo
  - Atmospherics
  - Medical
=======
  # Delta V - fuck all of this HoP is a service role
#  - Chemistry
#  - Engineering
#  - Research
#  - Detective
#  - Salvage
#  - Security # NoooOoOo!! My HoPcurity!1
#  - Brig
  - Lawyer
  - Cargo
#  - Atmospherics
#  - Medical
  - Boxer # DeltaV - Add Boxer access
  - Clown # DeltaV - Add Clown access
  - Library # DeltaV - Add Library access
  - Mime # DeltaV - Add Mime access
  - Musician # DeltaV - Add Musician access
  - Reporter # DeltaV - Add Reporter access
  - Zookeeper # DeltaV - Add Zookeeper access
>>>>>>> a2133335fb6e574d2811a08800da08f11adab31f
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: HoPGear
  equipment:
<<<<<<< HEAD
    shoes: ClothingShoesColorBrown
    id: HoPPDA
    gloves: ClothingHandsGlovesHop
    ears: ClothingHeadsetAltCommand
    belt: BoxFolderClipboard
=======
    jumpsuit: ClothingUniformJumpsuitHoP
    back: ClothingBackpackHOPFilled
    shoes: ClothingShoesLeather # DeltaV - HoP needs something better than plebe shoes.
    head: ClothingHeadHatHopcap
    id: HoPPDA
    gloves: ClothingHandsGlovesHop
    ears: ClothingHeadsetHoP # DeltaV - HoP is now a service role, replaces their all channels headset.
    belt: BoxFolderClipboard
  innerClothingSkirt: ClothingUniformJumpskirtHoP
  satchel: ClothingBackpackSatchelHOPFilled
  duffelbag: ClothingBackpackDuffelHOPFilled
>>>>>>> a2133335fb6e574d2811a08800da08f11adab31f
