- type: entity
  name: cleanades box
  parent: BoxCardboard
  id: BoxCleanerGrenades
  description: A box full of cleanades.
  components:
  - type: StorageFill
    contents:
      - id: CleanerGrenade
        amount: 4
  - type: Sprite
    layers:
      - state: box
<<<<<<< HEAD
      - state: flashbang
=======
      - state: flashbang
>>>>>>> a2133335fb6e574d2811a08800da08f11adab31f
