- type: gameMapPool
  id: DefaultMapPool
  maps:
<<<<<<< HEAD
  - Atlas
  - Bagel
  - Barratry
  - Box
  - Cluster
  - Core
  - Fland
  - Marathon
  - Meta
  - Oasis
  - Omega
  - Origin
  - Saltern
  - Packed
  - Reach
  - Train

  # Mapas do Pirata
  - Falcon
  - RadStation
  - Gaxstation
  - Glacier
  - Esperanza
  #- EstacaoPirata
=======
  - Arena
  - Asterisk
  - Core
  - Edge
  - Glacier
  - Hammurabi
  - Lighthouse
  - Pebble
  - Saltern
  - Shoukou
  - Submarine
  - Tortuga
  - TheHive
  - Glacier
  - Saltern
  - Gax
  - Rad
>>>>>>> a2133335fb6e574d2811a08800da08f11adab31f
