#Cult outfit startingGear definitions.
- type: startingGear
  id: CultLeaderGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBlack
    back: ClothingBackpackFilled
    head: ClothingHeadHelmetCult
    neck: BedsheetCult
    outerClothing: ClothingOuterArmorCult
    shoes: ClothingShoesCult
    id: PassengerPDA
    ears: ClothingHeadsetService
<<<<<<< HEAD
=======
  innerClothingSkirt: ClothingUniformJumpskirtColorBlack
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
>>>>>>> a2133335fb6e574d2811a08800da08f11adab31f

- type: startingGear
  id: CultistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBlack
    back: ClothingBackpackFilled
    head: ClothingHeadHatHoodCulthood
    outerClothing: ClothingOuterRobesCult
    shoes: ClothingShoesColorRed
    id: PassengerPDA
    ears: ClothingHeadsetService
<<<<<<< HEAD
=======
  innerClothingSkirt: ClothingUniformJumpskirtColorBlack
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
>>>>>>> a2133335fb6e574d2811a08800da08f11adab31f
