using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

<<<<<<< HEAD:Content.Client/Lobby/UI/HighlightedContainer.xaml.cs
namespace Content.Client.Lobby.UI;
=======
namespace Content.Client.Preferences.UI;
>>>>>>> a2133335fb6e574d2811a08800da08f11adab31f:Content.Client/Preferences/UI/HighlightedContainer.xaml.cs

[GenerateTypedNameReferences]
public sealed partial class HighlightedContainer : PanelContainer
{
    public HighlightedContainer()
    {
        RobustXamlLoader.Load(this);
    }
}
