- type: job
  id: Bartender
  name: job-name-bartender
  description: job-description-bartender
  playTimeTracker: JobBartender
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Civilian
<<<<<<< HEAD
      time: 3600 # Corvax-RoleTime
=======
      min: 3600 #DeltaV
>>>>>>> a2133335fb6e574d2811a08800da08f11adab31f
  startingGear: BartenderGear
  icon: "JobIconBartender"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  - Bar
  extendedAccess:
  - Kitchen
  - Hydroponics

- type: startingGear
  id: BartenderGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: BartenderPDA
    ears: ClothingHeadsetService
<<<<<<< HEAD
=======
  innerClothingSkirt: ClothingUniformJumpskirtBartender
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
>>>>>>> a2133335fb6e574d2811a08800da08f11adab31f
