- type: job
  id: Clown
  name: job-name-clown
  description: job-description-clown
  playTimeTracker: JobClown
  requirements:
<<<<<<< HEAD
  - !type:OverallPlaytimeRequirement
      time: 90000 # Corvax-RoleTime
=======
    - !type:CharacterOverallTimeRequirement # DeltaV - Playtime requirement
      min: 7200 #2 hrs
>>>>>>> a2133335fb6e574d2811a08800da08f11adab31f
  startingGear: ClownGear
  icon: "JobIconClown"
  supervisors: job-supervisors-hop
  access:
  - Theatre
  - Maintenance
  - Clown # DeltaV - Add Clown access
  special:
  - !type:AddComponentSpecial
    components:
    - type: Clumsy
      clumsyDamage:
        types: #literally just picked semi random valus. i tested this once and tweaked it.
          Blunt: 5
          Piercing: 4
        groups:
          Burn: 3
<<<<<<< HEAD
    - type: SleepEmitSound
      snore: /Audio/Voice/Misc/silly_snore.ogg
      interval: 10
=======
# DeltaV - Commenting out the clown snore sound because I am not fond of it (it makes me itchy and feral). By "I", I mean Leonardo_DaBepis.
#    - type: SleepEmitSound
#      snore: /Audio/Voice/Misc/silly_snore.ogg
#      interval: 10
>>>>>>> a2133335fb6e574d2811a08800da08f11adab31f
  - !type:AddImplantSpecial
    implants: [ SadTromboneImplant ]

- type: startingGear
  id: ClownGear
  equipment:
    mask: ClothingMaskClown
    pocket1: BikeHorn
    pocket2: ClownRecorder
    id: ClownPDA
    ears: ClothingHeadsetService