- type: job
  id: Librarian
  name: job-name-librarian
  description: job-description-librarian
  playTimeTracker: JobLibrarian
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Epistemics
      min: 14400
    - !type:CharacterLogicOrRequirement
      requirements:
        - !type:CharacterSpeciesRequirement
          inverted: true
          species:
            - IPC
        - !type:CharacterTraitRequirement
          traits:
            - AnomalousPositronics
  startingGear: LibrarianGear
  icon: "JobIconLibrarian"
  supervisors: job-supervisors-rd
  access:
  - Research
  - Maintenance
  - Library
  special:
  - !type:AddComponentSpecial
    components:
    - type: Psionic
    - type: InnatePsionicPowers
      powersToAdd:
        - XenoglossyPower
        - TelepathyPower


- type: startingGear
  id: LibrarianGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    outerClothing: ClothingOuterCoatRnd
    id: LibrarianPDA
    ears: ClothingHeadsetScience
    pocket1: d10Dice
<<<<<<< HEAD
    pocket2: HandLabeler # for making named bestsellers
=======
    pocket2: HandLabeler
  innerClothingSkirt: ClothingUniformJumpskirtLibrarian
  satchel: ClothingBackpackSatchelLibrarianFilled
  duffelbag: ClothingBackpackDuffelLibrarianFilled
>>>>>>> a2133335fb6e574d2811a08800da08f11adab31f
